name: Build and test PRs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.102'
          
      - name: Run tests netcoreapp3.1
        run: |
          dotnet build -c Release
          docker-compose -f tests/docker-compose.yml up -d
          dotnet test -c Release
          docker-compose -f tests/docker-compose.yml down
